Locales for 1.2.0
mahomaps/mm-v1 pull request #118
Opened 2023-06-26 00:20 UTC by Feodor0090

- [ ] Английски
- [ ] Французкий

2023-06-27 11:59 UTC, shinovon commented
нельзя класс/интерфейс с константами к локалям?

2023-06-27 12:37 UTC, Feodor0090 commented
Прогард всё это заинлайнит, так что почему бы и нет

но писать эту красоту буду точно не я.

2023-06-27 13:59 UTC, shinovon submitted a review, later dismissed
я не знаю что тут проверять

2023-06-27 15:31 UTC, Petrprogs requested changes
In this contex "Operating mode" must be "Opening hours"

2023-06-27 23:52 UTC, Feodor0090 commented
@Petrprogs I guess, now it's ready?

2023-06-28 09:42 UTC, Petrprogs commented
> @Petrprogs I guess, now it's ready?

Yeah, you can merge

2023-06-28 09:42 UTC, Petrprogs approved these changes

2023-06-28 14:57 UTC, merged